version: '3.10'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tennis-motion-analyzer
      POSTGRES_PASSWORD: tennis-motion-analyzer#123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data:rw
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/src
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    restart: always

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: superuser
      MINIO_ROOT_PASSWORD: superuser
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
  redis_data:
